### ISSUE TITLE
Eresources/Cataloging Workflow: Create brief instance records for new Coral items

### ISSUE THREAD

**Issue by ghost** [TAMULib/fw-registry#103]
Perl script that runs on 128.194.86.30 (highsmith.library.tamu.edu) to extract data for titles in Coral database that are not already represented in LibCat, format a basic MARC record for those titles, and upload the new MARC record. Uses Voyager BatchCat API.

Cron task to make requests to Coral and create stub instances in FOLIO if not yet existing.

**Comment by hismith** [comment]
The bulk of the requirements for this task are included in steps 1-4 of https://wikis.library.tamu.edu/display/DICS/Creating+short+records+for+database+scope. However, this process has an unprioritized prerequisite in https://voyagermis.tamu.edu/ser/uncataloged_db.php. The replication (or not) of VoyagerMIS reports is just beginning to be discussed.

**Comment by hismith** [comment]
Steps:
1. Rewrite this script: ringle.tamu.edu:/export/home/voyager/scripts/general/coral_extract.ksh in an appropriate language to download the coral data to the ldp.
2. Write another script to load the coral data into a table in the dev schema on the ldp.

3. Write a script to compare the dev.coral data to tamu folio data to: 1) identify the databases that are present in the coral data and absent from the tamu data; 2) create folio instance & holdings records that meet the criteria from step 1 and insert them into the folio database.
