### ISSUE TITLE
DivIT patron update workflow: test update

### ISSUE THREAD

**Issue by wwelling** [TAMULib/fw-registry#172]
Extract the entire file of eligible users, rather than limiting to the user records that have changed in the 3 previous days. Circulation relies on that update date to know how current the user's record is. For instance, if a student's record hasn't updated in 3 months they know that something is going on with the student's eligibility. Also, under the current system, people who are valid but whose record never changes (like me since 1993 when my address changed) would fall out periodically making more work all around.

**Comment by wwelling** [comment]
Record average of 5 executions.

**Comment by wwelling** [comment]
https://github.com/TAMULib/fw-registry/tree/172-patron-workflow-all-patrons

**Comment by hismith** [comment]
See Slack comment in migration channel on 1/28/2022. Some of the create counts look good, 'specially those in the 1,2,300 range. But the updates look low and suddenly there's a 98K update on 1/28/2022. It may just be the source database, but I'd appreciate a double-check
