### ISSUE TITLE
Shelflist (holdings level) report should send download links in email rather than attachment

### ISSUE THREAD

**Issue by jcreel** [TAMULib/fw-registry#227]

**Comment by jcreel** [comment]
We have a feeling this was partially addressed with this work: https://github.com/TAMULib/fw-registry/pull/201/commits/ea2b24c298d372dd41dc124f0bb9217a1b8d8600

**Comment by jeremythuff** [comment]
This has been completed already

**Comment by wwelling** [comment]
Issue was a result of confusion in what has already been implemented. See https://github.com/TAMULib/fw-registry/pull/201/commits/ea2b24c298d372dd41dc124f0bb9217a1b8d8600
