### ISSUE TITLE
PO Workflow: Items ingested being set to In Process after receiving in invoice app

### ISSUE THREAD

**Issue by wwelling** [TAMULib/fw-registry#259]
PO workflow sets all item status to `Available`.

This appears to be a bug with the logic of receiving action. Not sure why it would set from `Available` to `In Process` when the item is selected as received. It should just leave it as `Available`. 

Correction:

For Orders outside of the PO Workflow, when the PO is created, the item has a status of On order, then when it is received the status changes to In Process, then catalogers check in the item once they are done with it, and the status becomes available. Books brought in through the PO workflow are mostly shelf ready (little to no cataloging needed) and this is why we prefer the status of Available.

**Comment by jcreel** [comment]
We need some more investigation of this business process before working on a solution.  Could it be that the module can be configured to change to a different status (i.e. Available) when an item is received?

**Comment by wwelling** [comment]
When receiving an item from an order, the item status is set to `In Process` by default. This is described in the API and in a hover over tip in the UI during order receive.

https://s3.amazonaws.com/foliodocs/api/mod-orders/r/check-in.html#orders_check_in_post

![Image](https://user-images.githubusercontent.com/8352733/199074439-2e4aa419-10be-47c0-a798-b609ff14b495.png)



![Image](https://user-images.githubusercontent.com/8352733/199074504-7be81e25-c51f-4579-9085-fe8fee4f2631.png)

**Comment by wwelling** [comment]
The request payload to `/orders/check-in` already incorrectly set cehckInPieces itemStatus to `In Process`.


![Image](https://user-images.githubusercontent.com/8352733/199083043-04b27a82-5cc2-4481-ab4e-b9a04699580b.png)

**Comment by wwelling** [comment]
Here is the commit that caused the regression, https://github.com/folio-org/ui-receiving/commit/0476072489c301249317cc4821a3707979d56d9c#diff-d1eb5075b845af707ea8d46b7efc7314ed909a6b3b7d2d8c7033bf6dd948ba79R121.

**Comment by wwelling** [comment]
Here is the Jira ticket submitted for this regression:

https://issues.folio.org/browse/UIREC-249
