### ISSUE TITLE
Purchase Order Workflow generates exception on Dev and Demos

### ISSUE THREAD

**Issue by jcreel** [TAMULib/fw-registry#278]
Attempt to reproduce on Testing before pursuing issue further.
Purchase Order fails with "The Purchase Order Workflow report is currently unavailable.".  See https://tamulib.atlassian.net/wiki/spaces/Applications/pages/152240162/2023-02-09+Workflows+QA+Results.

**Comment by rmathew1011** [comment]
Exception happening at mod-camunda

```
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> username  [in template "body" at line 1, column 17]
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${username}  [in template "body" at line 1, column 15]
```
Code:

[Username](https://github.com/TAMULib/fw-cli/blob/main/src/config.ts#L27)

**Comment by rmathew1011** [comment]
Purchase Order Workflow successful once the File was uploaded. ( Sample mrc files uploaded in wiki QA template for further test purpose.)
Note: All fields are required - although all fields are marked as optional.
