### ISSUE TITLE
Med-Sci GPS workflow: SSL certificate issue

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/fw-registry#290]
Update:
`com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:62fa1fae-cce9-45e9-9d23-5428f4140f99`

Also exception related to the connection credentials:

`com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The TCP/IP connection to the host [mssql-prod3.library.tamu.edu](http://mssql-prod3.library.tamu.edu/), port 1433 has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall."`

**Comment by jcreel** [comment]
This is a manifestation of the more general issue of workflows not connecting to DIVIT (aka TS) databases (like the used to).
