### ISSUE TITLE
Circulation Workflow: Daily report from circ fines for Business Office to balance cash drawer

### ISSUE THREAD

**Issue by wwelling** [TAMULib/fw-registry#97]
Perl script that extracts data for all fines paid the previous day, who paid, how much, etc., and sends extract to  Business office staff, circ staff as email attachment to allow them to balance cash income. May be supplanted by FOLIO circulation in-app report to "balance cash drawer".

May have equivalent feature in FOLIO

daily cron

**Comment by hismith** [comment]
Here's the sql necessary for this task, based on the ldp:
select  distinct isp.name AS service_point,
      	actions.payment_method AS method,
        users.barcode,
        concat(users.data->'personal'->>'lastName', ' ', users.data->'personal'->>'firstName') AS name,
        to_timestamp(actions.date_action::text,'YYYY-MM-DD HH24:MI:SS') at time zone 'America/Chicago',
        actions.source AS operator,
      	actions.amount_action AS amount,
      	actions.comments AS comments,
      	actions.id
from    public.audit_circulation_logs logs,
      	public.inventory_service_points isp,
        public.user_users users,
      	public.feesfines_accounts accounts,
      	public.feesfines_feefineactions actions
where   actions.type_action in ('Paid fully','Paid partially')
and   	isp.id = logs.service_point_id
and   	logs.data->'linkToIds'->>'feeFineId' = accounts.id
and   	actions.user_id = users.id
and   	actions.account_id = accounts.id
and   	cast(logs.date AS date) = current_date-1
and   	isp.name in (
      	'Ask Us Desk (Evans)',
      	'Business Library Circulation',
      	'InterLibrary Loan Dept. (Evans)',
      	'Maps & GIS',
      	'Media and Reserves',
      	'PSEL Circulation Desk')
order by to_timestamp(actions.date_action::text,'YYYY-MM-DD HH24:MI:SS') at time zone 'America/Chicago' desc
;

**Comment by hismith** [comment]
Currently the output is sent out as an email attachment. The perl script referenced above will give you the addresses.

**Comment by doug-hahn** [comment]
I hope I got the right file from the depths of my email

[fees_fines.sql.txt](https://github.com/TAMULib/fw-registry/files/6718889/fees_fines.sql.txt)

**Comment by hismith** [comment]
That's one of them. There's also an overdues.sql

Anne L. Highsmith
979 862 4234
***@***.***
